/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef, useState } from "react";
import { Decal, useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    pizzaBox: THREE.Mesh;
    lid_1: THREE.Mesh;
    lid_1_1: THREE.Mesh;
  };
  materials: {
    _defaultMat: THREE.MeshStandardMaterial;
    ["frontFace.001"]: THREE.MeshStandardMaterial;
  };
};

export function PizzaBox(props: JSX.IntrinsicElements["group"]) {
  const texture = useTexture("/textures/wawa.png");

  const { nodes, materials } = useGLTF("/models/pizzaBox.glb") as GLTFResult;
  const [pos, setPos] = useState([-0.3, 0.5, 0]);
  const [rotation, setRotation] = useState([1, 1, 5.2]);
  const [scale, setScale] = useState([0.6, 0.6, 0.6]);

  return (
    <group {...props} dispose={null} scale={4}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pizzaBox.geometry}
        material={materials._defaultMat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lid_1.geometry}
        material={materials._defaultMat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lid_1_1.geometry}
        material={materials["frontFace.001"]}
      >
        <meshBasicMaterial transparent opacity={0} />
        <Decal
          debug // Makes "bounding box" of the decal visible
          position={pos} // Position of the decal
          rotation={rotation} // Rotation of the decal (can be a vector or a degree in radians)
          scale={scale} // Scale of the decal
        >
          <meshStandardMaterial
            map={texture}
            toneMapped={false}
            transparent
            polygonOffset
            polygonOffsetFactor={-1} // The mesh should take precedence over the original
          />
        </Decal>
      </mesh>
    </group>
  );
}

useGLTF.preload("/pizzaBox.glb");
